{
 "title": "Polkadot",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Validator instance",
   "type": "graph",
   "description": "Shows current validator instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_value{job=\"polkadot\"}",
     "legendFormat": "{{group_name}}|{{instance_id}}"
    }
   ]
  },
  {
   "title": "Disk usage in percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{job=\"polkadot\",path=\"/data\"}",
     "legendFormat": "{{group_name}}|{{instance_id}}"
    }
   ]
  },
  {
   "title": "P2P Heath state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_health_checks_critical{job=\"polkadot\",check_id=\"30333\"}",
     "legendFormat": "{{group_name}}|{{instance_id}}"
    }
   ]
  },
  {
   "title": "Swap usage in percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "swap_used_percent{job=\"polkadot\"}",
     "legendFormat": "{{group_name}}|{{instance_id}}"
    }
   ]
  },
  {
   "title": "Health status",
   "type": "graph",
   "description": "Health status. 0 values denote that the instance is healthy",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "health_value{job=\"polkadot\"}",
     "legendFormat": "{{group_name}}|{{instance_id}}"
    }
   ]
  },
  {
   "title": "Memory usage percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{job=\"polkadot\"}",
     "legendFormat": "{{group_name}}|{{instance_id}}"
    }
   ]
  }
 ]
}