linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - gofmt
    - golint
    - goimports
    - unparam
    - unconvert
    - interfacer
    - megacheck
    - staticcheck
    - unused
    - gosimple
    - dupl
    - goconst
    - gocyclo
    - nakedret
    - scopelint
    - misspell
    - gosec